update `quat(::Array)` to return `Array{<:Quaternion}`
JuliaGeometry/Quaternions.jl pull request #95
Opened 2022-09-16 18:24 UTC by hyrodium

This PR fixes #94.
Note that this PR is considered as a breaking change.

https://github.com/JuliaGeometry/Quaternions.jl/blob/0be4cdd881872e14b480bdb69326f188f4b40236/test/Quaternion.jl#L112-L113

2022-09-17 14:25 UTC, hyrodium commented on src/Quaternion.jl
> +end
This implementation is the same as 
https://github.com/JuliaLang/julia/blob/1ece3f64e093ba47bcd5e7a01193b8c9b05d441e/base/complex.jl#L1114-L1119

2022-09-24 15:02 UTC, hyrodium commented
I'm keeping this PR draft because I'm not sure whether the `quat` behavior in #94 is intended or not.

2022-12-01 14:22 UTC, hyrodium commented
I'll remove some methods such as 
```julia
function Quaternion(s::Real, a::AbstractVector)
    Base.depwarn("`Quaternion(s::Real, a::AbstractVector)` is deprecated and will be removed in the next breaking release (v0.7.0). Please use `Quaternion(s, a[1], a[2], a[3])` instead.", :Quaternion)
    Quaternion(s, a[1], a[2], a[3])
end
```
after merging #111 and #113 to avoid making conflicts.

2022-12-07 08:47 UTC, sethaxen requested changes
LGTM, just 2 fixes needed.

2022-12-07 08:47 UTC, sethaxen commented on src/Quaternion.jl
>  quat(s, a) = Quaternion(s, a)
This method now leads nowhere and should also be deleted.
```suggestion
```

2022-12-07 08:47 UTC, sethaxen commented on src/Quaternion.jl
> +        error("`quat` not defined on abstractly-typed arrays; please convert to a more specific type")
Can you add a test for this error?

2022-12-07 12:35 UTC, hyrodium commented on src/Quaternion.jl
> +        error("`quat` not defined on abstractly-typed arrays; please convert to a more specific type")
Done!

2022-12-07 12:48 UTC, sethaxen approved these changes
LGTM!

2022-12-07 12:59 UTC, merged